// Platzi/JavaScript/frameworks-libraries/svelte-app/App.svelte
<script>
  import Form from "./Form";
  import { Title } from "./styles";
</script>

<style>
  :global(body) {
    --bg: #ffe9c5;
    --color: #e54b00;
    --color-dark: #512613;

    background-color: var(--bg);
    color: var(--color);
    font-family: sans-serif;
    margin: 0;
  }
</style>

<main>
	<h2 class="{Title}">Películas</h2>
  <Form />
</main>

// Platzi/JavaScript/frameworks-libraries/vue-app/src/App.vue
<template>
  <h2>Películas</h2>
  <Form />
</template>

<script>
import Form from "./components/Form.vue";

export default {
  name: "App",

  components: {
    Form: Form,
  },
};
</script>

<style lang="scss">
@import "./styles/_variables.scss";

html,
body {
  background-color: $bg;
  color: $color;
  margin: 0;
  font-family: sans-serif;
}

h2 {
  border-bottom: 1px solid $color;
  padding: 0 10px 15px;
}
</style>
