// JavaScript/frameworks-libraries/angular-app/src/app/app.component.ts
import { Component } from "@angular/core";

type Movie = {
  name: String;
  available: Number;
  quantity: number;
};

type Movies = Array<Movie>;

@Component({
  selector: "app-root",
  templateUrl: "./app.component.html",
  styleUrls: ['./app.component.css']
})
export class AppComponent {
  title: String = "Películas";
  movies: Movies = [
    {
      name: "Avengers",
      available: 3,
      quantity: 0
    },
    {
      name: "Terminator",
      available: 5,
      quantity: 0
    }
  ];

  addMovieQuantity(movieName) {
    const movieIndex = this.movies.findIndex(
      (movie) => movie.name === movieName
    );

    this.movies[movieIndex].quantity++;
  }

  removeMovieQuantity(movieName) {
    const movieIndex = this.movies.findIndex(
      (movie) => movie.name === movieName
    );

    this.movies[movieIndex].quantity--;
  }
}

<h2>{{ title }}</h2>

<form *ngFor="let movie of movies">
  <h3>{{ movie.name }}</h3>

  <button
    type="button"
    (click)="removeMovieQuantity(movie.name)"
    [disabled]="movie.quantity <= 0"
  >
    -
  </button>

  {{ movie.quantity }}

  <button
    type="button"
    (click)="addMovieQuantity(movie.name)"
    [disabled]="movie.quantity >= movie.available"
  >
    +
  </button>
</form>

// Platzi/JavaScript/frameworks-libraries/react-app/src/App.js
import React from 'react';
import { Theme } from "./Theme";
import { Title } from "./Title";
import Form from "./Form";

const movies = [
  {
    name: "Avengers",
    available: 5
  },
  {
    name: "Terminator",
    available: 3
  }
];

export default function App() {
  const [theme, setTheme] = React.useState("avengers");
  
  return (
    <Theme theme={theme}>
      <h2>Películas</h2>
      {movies.map((movie) => (
        <Form 
          movie={movie} 
          updateTheme={() => setTheme(movie.name)}
        />
      ))}
    </Theme>
  );
}
